
trigger:
  batch: true
  branches:
    include:
    - master
    #- develop

pool:
  name: "Self-Hosted-LIN-Agent-Pool-Avijit"
  # "Hosted"
  vmImage: ubuntu-latest'

steps:
- task: Bash@3
  displayName: "Display intermediate artifacts"
  inputs:
    targetType: 'inline'
    script: |
      pwd
      pth=$(System.DefaultWorkingDirectory)
      ls
      echo "cd path: " $pth
      cd $pth
      ls
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    # testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: Bash@3
  displayName: "Display intermediate artifacts"
  inputs:
    targetType: 'inline'
    script: |
      pwd
      pth=$(System.DefaultWorkingDirectory)
      ls
      echo "cd path: " $pth
      cd $pth
      ls
      echo "------------ ls target -------------"
      pwd
      pth=$(System.DefaultWorkingDirectory)/target
      ls
      echo "Target path: " $pth
      cd $pth
      ls

- script: ansible-playbook ./playbook.yaml  -i ./inventory.ini
  displayName: "ansible-playbook ./playbook.yaml  -i ./inventory.ini"