
trigger:
  batch: true
  branches:
    include:
    - master
    #- develop

pool:
  name: "Self-Hosted-LIN-Agent-Pool-Avijit"
  # "Hosted"
  vmImage: ubuntu-latest'

steps:
- task: Bash@3
  displayName: "Display intermediate artifacts"
  inputs:
    targetType: 'inline'
    script: |
      pwd
      pth=$(System.DefaultWorkingDirectory)
      ls
      echo "cd path: " $pth
      cd $pth
      ls
# - task: Maven@3
#   inputs:
#     mavenPomFile: 'pom.xml'
#     mavenOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '13'
#     jdkArchitectureOption: 'x64'
#     publishJUnitResults: true
#     # testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     goals: 'package'

- task: Bash@3
  displayName: "Display intermediate artifacts"
  inputs:
    targetType: 'inline'
    script: |
      pwd
      pth=$(System.DefaultWorkingDirectory)
      ls
      echo "cd path: " $pth
      cd $pth
      ls
      echo "------------ ls target -------------"
      pwd
      pth=$(System.DefaultWorkingDirectory)/target
      ls
      echo "Target path: " $pth
      cd $pth
      ls

# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '3.x'
#     architecture: 'x64'

# - script: pip install -r requirements.txt
#   displayName: 'Install Python packages'

- task: UsePythonVersion@0
  displayName: 'Install Python with UsePythonVersion@0'
  inputs:
    versionSpec: '3.13'
    architecture: 'x64'

- task: Bash@3
  displayName: 'Install pip with python get-pip.py'
  inputs:
    targetType: 'inline'
    script: |
      python get-pip.py

# - script: pip install ansible[azure]
#   displayName: 'Install Ansible and the Azure modules'

- script: ansible-playbook ./playbook.yaml  -i ./inventory.ini
  displayName: "ansible-playbook ./playbook.yaml  -i ./inventory.ini"